version: '3.8'

services:
  nginx:
    image: local-nginx
    ports:
      - "80:80"			# Integral values are requried. Rewrote eighty as 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf		# Fixed confi to conf
    networks:
      - nginx-network

  python-app:
    image: local-python-app
    container_name: python_app
    expose:
      - "8000"				# Integral values are requried. Rewrote eight thousand as 8000
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge                       # Fixed spelling for bridge and removed options as options field is not valid for 'networks' as per our error logs.
