FROM python:3.9

WORKDIR /app                         
# Fixed appp to app.

COPY app.py /app				
# fixed appy to app.

RUN pip install flask netifaces             
# Fixed lib name to netifaces.

EXPOSE 8000			
# Converted to integer

CMD ["python", "app.py"]   
# Fixed typo 'python'
